config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about', to: 'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books
  resources :homes
  resources :users
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @user = current_user
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
   else
    render :index
   end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.new
    @book_detail = Book.find(params[:id])
    @user = @book_detail.user
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
   unless @book.user.id == current_user.id
    redirect_to books_path
   end
  end

  def update
    user = User.find(params[:id])
   unless user.id == current_user.id
    redirect_to books_path
   end

    @book = Book.find(params[:id])
   if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
   else
    render :edit
   end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
 <h2>User info</h2>

  <div>
    <%= image_tag user.get_image, size: "100x100" %>
    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>
    <div class="row">
        <%= link_to edit_user_path(user.id),class: "btn btn-outline-secondary btn-block" do %>
         <i class="fas fa-user-cog" aria-hidden="true"></i>
        <% end %>
    </div>
  </div>

 <h2 class="mt-3">New book</h2>

 <%= form_with model: book do |f| %>
  <div class="form-group">
   <%= f.label :title %>
   <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
   <%= f.label :opinion %>
   <%= f.text_field :body, class:  "form-control book-body" %>
  </div>
  <div class="form-group">
   <%= f.submit 'Create Book',class: "btn btn-success" %>
  </div>
 <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

   <h1>Editing Book</h1>
    <% if @book.errors.any? %>
     <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
      <ul>
     <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
     <% end %>
      </ul>
    <% end %>

   <%= form_with model: @book do |f|%>
    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control book_title" %>
    </div>
    <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: "form-control book-body" %>
    </div>
    <div class="form-group">
    <%= f.submit 'Update Book', class: "btn btn-success" %>
    </div>
   <% end %>

   <%= link_to "Show", book_path(@book.id) %> |
   <%= link_to "Back", books_path %>
  </div>
 </div>
</div>

app/views/books/index.html.erb
 <div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
   <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
   <ul>
    <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
   </ul>
  <% end %>
   <div class="row">
    <%= render 'list', user: @user, book: @book %>
     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
       <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
               <%= link_to user_path(book.id) do %>
                <%= image_tag book.user.get_image, size: "80x80" %>
               <% end %>
              </td>
              <td>
                <a>
                <%= link_to book_path(book.id) do %>
                 <%= book.title %>
                <% end %>
                </a>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
       </table>
      </div>
     </div>
  </div>

app/views/books/show.html.erb
 <div class="container px-5 px-sm-0">
   <div class="row">
    <%= render 'list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
     <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td>
              <%= image_tag @book_detail.user.get_image, size: "80x80" %><br>
              <%= link_to user_path(@user.id) do %>
               <%= @book_detail.user.name %>
              <% end %>
            </td>
            <td>
             <%= link_to book_path(@book_detail.id) do %>
              <%= @book_detail.title %>
             <% end %>
            </td>
            <td><%= @book_detail.body %></td>
            <td>
             <% if @book_detail.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book_detail.id),class: "btn btn-sm btn-success" %>
             <% end %>
            </td>
            <td>
             <% if @book_detail.user == current_user %>
              <%= link_to "Destroy", book_path(@book_detail.id), method: :delete, "data-confirm" => "本当に削除しますか？",class: "btn btn-sm btn-danger" %>
             <% end %>
            </td>
          </tr>
      </tbody>
     </table>
    </div>
   </div>
 </div>