config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about', to: 'homes#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books
  resources :homes
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/cb4dfc7c9e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
            <span>
              <%= link_to root_path,class: "navbar-brand" do %>
             Bookers
              <% end %>
            </span>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
           </button>
          <% if user_signed_in? %>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
             <li>
               <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
               <i class="fas fa-home" aria-hidden="true"></i>Home
               <% end %>
             </li>
             <li>
               <%= link_to users_path, class: "nav-link text-light" do %>
                <i class="fas fa-users" aria-hidden="true"></i>Users
               <% end %>
             </li>
             <li>
                <%= link_to books_path, class: "nav-link text-light" do %>
                 <i class="fas fa-book-open" aria-hidden="true"></i>Books
                <% end %>
             </li>
               <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                <i class="fas fa-sign-out-alt" aria-hidden="true"></i>Log out
               <% end %>
             </li>
           </ul>
          </div>
          <% else %>
           <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
             <li>
               <%= link_to root_path, class: "nav-link text-light" do %>
                <i class="fas fa-home" aria-hidden="true"></i>Home
               <% end %>
             </li>
             <li>
               <%= link_to home_about_path, class: "nav-link text-light" do %>
                <i class="fas fa-link" aria-hidden="true"></i>About
               <% end %>
             </li>
             <li>

               <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                <i class="fas fa-user-plus" aria-hidden="true"></i>Sign up
               <% end %>
             </li>
             <li>
               <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                <i class="fas fa-sign-in-alt" aria-hidden="true"></i>Log in
               <% end %>
             </li>
            </ul>
           </div>
        <% end %>
       </div>
      </nav>
    </header>
    <%= flash[:notice] %>
    <%= yield %>
    <footer>
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>